.prospector.yaml, inlineplz/interfaces/github.py, inlineplz/main.py, requirements_dev.txt
=> return nonzero exit code when there are messages to post

.travis.yml, inlineplz/env/local.py, inlineplz/linters/__init__.py, inlineplz/main.py, inlineplz/message.py, tests/parsers/test_prospector.py, tests/testdata/parsers/prospector.txt
=> automatically detect and run linters based on dotfiles

inlineplz/linters/__init__.py, inlineplz/parsers/prospector.py, tests/parsers/test_prospector.py, tests/testdata/parsers/prospector.txt
=> refactor prospector parser to use json format

inlineplz/interfaces/github.py, inlineplz/linters/__init__.py, inlineplz/message.py, inlineplz/parsers/eslint.py, inlineplz/parsers/jscs.py, inlineplz/parsers/jshint.py, inlineplz/parsers/prospector.py, tests/parsers/test_eslint.py, tests/parsers/test_jscs.py, tests/parsers/test_jshint.py, tests/parsers/test_prospector.py
=> add message.Messages and refactor comments to set

inlineplz/linters/__init__.py, inlineplz/parsers/jshint.py
@midniteio this fixes #54 (for real this time)
=> fix jshint parser and run command

inlineplz/message.py, inlineplz/parsers/jshint.py
=> xml parsing has special behavior for single files

inlineplz/linters/__init__.py, inlineplz/parsers/__init__.py, inlineplz/parsers/jsonlint.py, tests/parsers/test_jsonlint.py
=> add jsonlint support

inlineplz/linters/__init__.py, inlineplz/parsers/__init__.py, inlineplz/parsers/yamllint.py, tests/parsers/test_yamllint.py
=> add yaml-lint support

inlineplz/linters/__init__.py, inlineplz/parsers/__init__.py, inlineplz/parsers/rstlint.py, tests/parsers/test_rstlint.py
=> add rst-lint support

inlineplz/linters/__init__.py, inlineplz/parsers/__init__.py, inlineplz/parsers/markdownlint.py, tests/parsers/test_markdownlint.py, tests/testdata/parsers/markdownlint.txt
=> add markdownlint support

.travis.yml, inlineplz/main.py, inlineplz/parsers/jsonlint.py, inlineplz/parsers/markdownlint.py, inlineplz/parsers/yamllint.py
=> better error handling

inlineplz/linters/__init__.py
@midniteio @efokschaner :facepalm:
=> remove bad whitespace from stylint dotfile name

inlineplz/linters/__init__.py
a primitive method for tracking performance :smile_cat:
=> print installation and lint durations

inlineplz/linters/__init__.py, inlineplz/main.py, setup.py
=> improve performance

inlineplz/util/git.py
=> tell utf-8 encoder to replace errors

inlineplz/interfaces/github.py, inlineplz/message.py
@raphaelcastaneda how's this for a better version of https://github.com/guykisel/inline-plz/pull/114?
=> handle null/zero line numbers

inlineplz/linters/__init__.py, inlineplz/parsers/rflint.py, tests/parsers/test_rflint.py
=> configure rflint to run per file

inlineplz/linters/__init__.py
eslint already autoruns and provides the same feedback.
=> Set jscs autorun to False

inlineplz/linters/__init__.py
@vsiakka can you test this to see if it resolves your issue?
=> stringify error output

inlineplz/linters/__init__.py, inlineplz/parsers/__init__.py, inlineplz/parsers/dockerfilelint.py
=> add dockerfile_lint

inlineplz/linters/__init__.py, inlineplz/main.py, inlineplz/parsers/__init__.py, inlineplz/parsers/shellcheck.py
=> add shellcheck

inlineplz/linters/__init__.py
=> #146 run 'bundle install' during ruby gem installs

.inlineplz.yml, README.rst, inlineplz/linters/__init__.py, inlineplz/main.py
=> enable or disable linters in yaml

inlineplz/linters/__init__.py
=> fix path to markdownlint

inlineplz/linters/__init__.py, inlineplz/main.py
=> add --trusted flag for installs

inlineplz/parsers/jsonlint.py, inlineplz/parsers/markdownlint.py, inlineplz/parsers/rflint.py, inlineplz/parsers/yamllint.py
related to #159 but might not fully resolve it
=> catch index errors in some parsers

inlineplz/interfaces/github.py
Instead of just checking PR status at the start of commenting, check every ten seconds while we're posting comments to make sure we're not out of date.
=> check PR status every ten seconds

inlineplz/interfaces/github.py, inlineplz/linters/__init__.py, inlineplz/util/system.py
goes with https://github.com/guykisel/inline-plz-bot/pull/37
=> watch for a stopfile to stop execution

.travis.yml, inlineplz/interfaces/github.py, inlineplz/main.py, inlineplz/message.py
fixes #180 
also included a few minor debugging message improvements
=> replace backticks with single quotes in messages

inlineplz/linters/config/.eslintrc.js, inlineplz/linters/config/.gherkin-lintrc
=> fix default eslint and gherkin lint configs

inlineplz/interfaces/github.py, inlineplz/main.py
=> ignore paths when posting comments

inlineplz/env/local.py, inlineplz/main.py, inlineplz/util/git.py, setup.py
fix for https://github.com/matiasb/python-unidiff/issues/54
=> don't strip diffs

inlineplz/linters/__init__.py
=> install glide in strip-vendor mode

inlineplz/bin/codenarc/codenarc.xml
if people care about this they can run eclint
=> disable trailing whitespace rule

DEVELOPMENT.md
=> add a dev instructions doc

inlineplz/linters/__init__.py
https://github.com/Yelp/detect-secrets/blob/master/CHANGELOG.md my fix got merged
=> install detect-secrets from pypi

inlineplz/interfaces/github.py
=> Preserve comments people have replied to

inlineplz/interfaces/github.py, inlineplz/linters/__init__.py, inlineplz/linters/eclint.py, inlineplz/linters/isort.py, inlineplz/linters/prettier.py, inlineplz/linters/sh.py
=> add more autofixers

inlineplz/interfaces/github.py, inlineplz/message.py
=> dont try to post messages on files not in pr

inlineplz/interfaces/github.py, inlineplz/linter_runner.py
todo: should also lock around files when running per file to keep multiple tools from accessing the same file at the same time
=> dont run a tool more than once per file
